import os
import json
import logging
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn

def set_cell_background(cell, color_hex):
    """Set the background color of a table cell in DOCX."""
    shading_xml = f'<w:shd {nsdecls("w")} w:fill="{color_hex}"/>'
    cell._tc.get_or_add_tcPr().append(parse_xml(shading_xml))

def set_cell_margins(cell, top=100, bottom=100, left=150, right=150):
    """Set padding/margins for cell spacing."""
    tcPr = cell._tc.get_or_add_tcPr()
    tcMar = OxmlElement('w:tcMar')
    for m, val in [('w:top', top), ('w:bottom', bottom), ('w:left', left), ('w:right', right)]:
        node = OxmlElement(m)
        node.set(qn('w:w'), str(val))
        node.set(qn('w:type'), 'dxa')
        tcMar.append(node)
    tcPr.append(tcMar)

def generate_docx_report(scan_data: dict, output_dir: str = "reports") -> str:
    """Generates a professional, beautifully styled Word (.docx) assessment report from scan session records."""
    os.makedirs(output_dir, exist_ok=True)
    
    scan_id = scan_data.get("id", "0")
    target_url = scan_data.get("target_url", "N/A")
    timestamp_str = scan_data.get("timestamp", datetime.now().isoformat())
    try:
        dt = datetime.fromisoformat(timestamp_str)
        formatted_date = dt.strftime("%B %d, %Y at %I:%M %p")
    except Exception:
        formatted_date = timestamp_str
        
    doc = Document()
    
    # ----------------------------------------------------
    # Document Styling / Themes
    # ----------------------------------------------------
    # Base colors
    primary_color = RGBColor(31, 78, 121)     # Deep Corporate Navy
    secondary_color = RGBColor(127, 127, 127) # Grey
    dark_grey = RGBColor(51, 51, 51)
    
    # Configure default styles
    style_normal = doc.styles['Normal']
    style_normal.font.name = 'Segoe UI'
    style_normal.font.size = Pt(11)
    style_normal.font.color.rgb = dark_grey
    
    # ----------------------------------------------------
    # Title Page
    # ----------------------------------------------------
    # Top spacing
    for _ in range(3):
        doc.add_paragraph()
        
    # Main Title
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_p.add_run("AGENTIC QA AUTOMATION & SECURITY AUDIT REPORT")
    title_run.font.size = Pt(26)
    title_run.font.bold = True
    title_run.font.color.rgb = primary_color
    
    # Subtitle
    subtitle_p = doc.add_paragraph()
    subtitle_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = subtitle_p.add_run("Continuous Quality Validation and Vulnerability Assessment")
    sub_run.font.size = Pt(14)
    sub_run.font.italic = True
    sub_run.font.color.rgb = secondary_color
    
    for _ in range(5):
        doc.add_paragraph()
        
    # Metadata Box
    meta_p = doc.add_paragraph()
    meta_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    meta_p.add_run("Target URL: ").bold = True
    meta_p.add_run(f"{target_url}\n")
    meta_p.add_run("Scan ID Reference: ").bold = True
    meta_p.add_run(f"#{scan_id}\n")
    meta_p.add_run("Date of Assessment: ").bold = True
    meta_p.add_run(f"{formatted_date}\n")
    meta_p.add_run("Generated By: ").bold = True
    meta_p.add_run("Autonomous Multi-Agent Testing Pipeline (Antigravity Core)")
    
    doc.add_page_break()
    
    # ----------------------------------------------------
    # Section 1: Executive Summary
    # ----------------------------------------------------
    h1 = doc.add_paragraph()
    h1_run = h1.add_run("1. Executive Summary")
    h1_run.font.size = Pt(18)
    h1_run.font.bold = True
    h1_run.font.color.rgb = primary_color
    
    vulns = scan_data.get("vulnerabilities", [])
    tests = scan_data.get("test_cases", [])
    
    high_count = sum(1 for v in vulns if v["severity"] == "High")
    med_count = sum(1 for v in vulns if v["severity"] == "Medium")
    low_count = sum(1 for v in vulns if v["severity"] == "Low")
    info_count = sum(1 for v in vulns if v["severity"] == "Informational")
    
    summary_p = doc.add_paragraph()
    summary_p.add_run(
        f"On {formatted_date}, the autonomous agent network executed a hybrid Quality Assurance (QA) "
        f"and security assessment scan against the web application hosted at "
    )
    summary_p.add_run(f"{target_url}").bold = True
    summary_p.add_run(
        ". The primary objective was to map inputs/forms, generate AI-driven regression tests "
        "covering edge cases, and scan the application footprint for OWASP Top 10 vulnerabilities."
    )
    
    # Insert visual stat blocks in bullet form
    doc.add_paragraph().add_run("Summary of Findings:").bold = True
    
    bp1 = doc.add_paragraph(style='List Bullet')
    bp1.add_run("Functional Regression Test Cases: ").bold = True
    bp1.add_run(f"{len(tests)} scenarios successfully generated and cataloged (Positive, Negative, and Boundaries).")
    
    bp2 = doc.add_paragraph(style='List Bullet')
    bp2.add_run("Security Findings: ").bold = True
    bp2.add_run(f"{len(vulns)} issues detected. ")
    bp2.add_run(f"({high_count} High, {med_count} Medium, {low_count} Low, {info_count} Informational).").bold = True
    
    doc.add_paragraph() # Spacing
    
    # ----------------------------------------------------
    # Section 2: AI-Generated Functional Test Cases
    # ----------------------------------------------------
    h2 = doc.add_paragraph()
    h2_run = h2.add_run("2. AI-Driven Quality Assurance Test Suites")
    h2_run.font.size = Pt(18)
    h2_run.font.bold = True
    h2_run.font.color.rgb = primary_color
    
    doc.add_paragraph(
        "The Test Case Generator Agent analyzed the scraped DOM tree and designed comprehensive "
        "functional, boundary, and negative integration tests. These validation scenarios cover standard "
        "user flows and error paths."
    )
    
    if not tests:
        doc.add_paragraph("No test cases generated for this target.").italic = True
    else:
        # Create Table for Test Cases
        table = doc.add_table(rows=1, cols=4)
        table.style = 'Light Shading Accent 1'
        
        # Header Row
        hdr_cells = table.rows[0].cells
        headers = ["ID", "Category", "Test Scenario", "Expected Outcome"]
        col_widths = [Inches(0.6), Inches(1.2), Inches(2.7), Inches(2.5)]
        
        for i, header_text in enumerate(headers):
            hdr_cells[i].text = header_text
            set_cell_background(hdr_cells[i], "1F4E79")
            set_cell_margins(hdr_cells[i])
            run = hdr_cells[i].paragraphs[0].runs[0]
            run.font.bold = True
            run.font.color.rgb = RGBColor(255, 255, 255)
            hdr_cells[i].width = col_widths[i]
            
        # Data Rows
        for index, tc in enumerate(tests, start=1):
            row_cells = table.add_row().cells
            row_cells[0].text = f"TC-{index}"
            row_cells[1].text = tc.get("category", "General")
            row_cells[2].text = f"{tc.get('test_name', 'Test')}\n\nSteps:\n{tc.get('steps', '')}"
            row_cells[3].text = tc.get("expected_result", "Success")
            
            # Apply styling & margins
            for i in range(4):
                set_cell_margins(row_cells[i])
                row_cells[i].width = col_widths[i]
                
            # Soft grey stripes for even rows
            if index % 2 == 0:
                for cell in row_cells:
                    set_cell_background(cell, "F2F2F2")

    doc.add_paragraph() # Spacing
    doc.add_page_break()
    
    # ----------------------------------------------------
    # Section 3: Vulnerability & Security Assessment
    # ----------------------------------------------------
    h3 = doc.add_paragraph()
    h3_run = h3.add_run("3. Security Scan & OWASP Vulnerability Analysis")
    h3_run.font.size = Pt(18)
    h3_run.font.bold = True
    h3_run.font.color.rgb = primary_color
    
    doc.add_paragraph(
        "The Security Scan Agent performed structural and payload inspections on the target endpoint. "
        "Discovered vulnerabilities were classified and prioritized by impact risk."
    )
    
    if not vulns:
        doc.add_paragraph("No vulnerabilities discovered! Target matches modern secure configurations.").italic = True
    else:
        # Create Table for Vulns
        vuln_table = doc.add_table(rows=1, cols=4)
        vuln_table.style = 'Light Shading Accent 1'
        
        hdr_cells = vuln_table.rows[0].cells
        vuln_headers = ["Severity", "Vulnerability Name", "Description & Location", "Remediation Strategy"]
        vuln_widths = [Inches(1.0), Inches(2.0), Inches(2.2), Inches(2.3)]
        
        for i, header_text in enumerate(vuln_headers):
            hdr_cells[i].text = header_text
            set_cell_background(hdr_cells[i], "1F4E79")
            set_cell_margins(hdr_cells[i])
            run = hdr_cells[i].paragraphs[0].runs[0]
            run.font.bold = True
            run.font.color.rgb = RGBColor(255, 255, 255)
            hdr_cells[i].width = vuln_widths[i]
            
        # Map severity colors
        severity_colors = {
            "High": "FFC7CE",        # Soft Red
            "Medium": "FFEB9C",      # Soft Orange
            "Low": "FFF2CC",         # Soft Yellow
            "Informational": "E2EFDA" # Soft Green/Grey
        }
        severity_text_colors = {
            "High": RGBColor(156, 0, 6),
            "Medium": RGBColor(156, 101, 0),
            "Low": RGBColor(128, 128, 0),
            "Informational": RGBColor(55, 86, 35)
        }
        
        for idx, v in enumerate(vulns, start=1):
            row_cells = vuln_table.add_row().cells
            
            # Severity Pill formatting
            sev = v.get("severity", "Low")
            row_cells[0].text = sev
            set_cell_background(row_cells[0], severity_colors.get(sev, "FFFFFF"))
            p_run = row_cells[0].paragraphs[0].runs[0]
            p_run.font.bold = True
            p_run.font.color.rgb = severity_text_colors.get(sev, dark_grey)
            
            row_cells[1].text = v.get("name", "Vulnerability")
            row_cells[1].paragraphs[0].runs[0].font.bold = True
            
            desc_text = v.get("description", "")
            if v.get("url_path"):
                desc_text += f"\n\nAffects Path:\n{v.get('url_path')}"
            row_cells[2].text = desc_text
            
            row_cells[3].text = v.get("remediation", "")
            
            # Style layouts
            for i in range(4):
                set_cell_margins(row_cells[i])
                row_cells[i].width = vuln_widths[i]
                if i > 0 and idx % 2 == 0:
                    set_cell_background(row_cells[i], "F9F9F9")

    # ----------------------------------------------------
    # Section 4: Audit Verification & Agent Logs
    # ----------------------------------------------------
    doc.add_page_break()
    h4 = doc.add_paragraph()
    h4_run = h4.add_run("4. Audit Trail & Short-Term Agent Collaboration Logs")
    h4_run.font.size = Pt(18)
    h4_run.font.bold = True
    h4_run.font.color.rgb = primary_color
    
    doc.add_paragraph(
        "Below is the system execution audit log recorded during the multi-agent collaboration cycle. "
        "This records the handshake and data passing sequence across agents."
    )
    
    interactions = scan_data.get("agent_interactions", [])
    if not interactions:
        doc.add_paragraph("No audit logs captured during this run.").italic = True
    else:
        for idx, inter in enumerate(interactions):
            agent_name = inter.get("agent_name", "System")
            msg = inter.get("message", "")
            time_log = inter.get("timestamp", "")
            
            log_p = doc.add_paragraph()
            log_p.paragraph_format.left_indent = Inches(0.2)
            
            run_lbl = log_p.add_run(f"[{time_log.split('T')[-1][:8]}] {agent_name}: ")
            run_lbl.font.bold = True
            run_lbl.font.color.rgb = primary_color
            
            log_p.add_run(msg)
            
    # Save the file
    filename = f"QA_Security_Report_Scan_{scan_id}.docx"
    filepath = os.path.join(output_dir, filename)
    doc.save(filepath)
    logging.info(f"Report compiled successfully and written to: {filepath}")
    return filepath

if __name__ == "__main__":
    # Local report test
    test_data = {
        "id": 99,
        "target_url": "https://example-shop.com",
        "timestamp": datetime.now().isoformat(),
        "test_cases": [
            {"category": "Positive", "test_name": "Login Form Input", "steps": "Enter valid email and pass, click submit", "expected_result": "Logged in dashboard loaded"},
            {"category": "Negative", "test_name": "Login Blank Password", "steps": "Enter valid email, leave password blank, click submit", "expected_result": "Inline validation message triggered"}
        ],
        "vulnerabilities": [
            {"name": "SQL Injection", "severity": "High", "description": "Parameters exposed to SQLite backend.", "url_path": "https://example-shop.com/api/products?id=1", "remediation": "Use SQLAlchemy ORM parameterized requests."},
            {"name": "Missing HSTS Header", "severity": "Low", "description": "HSTS not set on header", "url_path": "https://example-shop.com/", "remediation": "Add STS header."}
        ],
        "agent_interactions": [
            {"agent_name": "Test Case Agent", "message": "Scraped DOM and found login form. Generating scenarios.", "timestamp": datetime.now().isoformat()},
            {"agent_name": "Security Agent", "message": "Triggering port scans and SQL injections against endpoints.", "timestamp": datetime.now().isoformat()}
        ]
    }
    generate_docx_report(test_data)
